apiVersion: v1
kind: Secret
metadata:
  name: cloudinit-with-nginx-secret
  namespace: dev
stringData:
  userdata: |-
              #cloud-config
              ssh_pwauth: true
              write_files:
                - path: /root/install-nginx.sh
                  content: |
                      #! /bin/bash                  
                      ## Install nginx on a KubeVirt VM
                      apt-get update && apt-get install nginx -y
                      ## set a custome nginx welcome page 
                      echo "Hello KubeVirts!!, I am being served from $(hostname)" | tee  /var/www/html/index.nginx-debian.html
                      ## start nginx service
                      service nginx start
                  permissions: '0755'
                  owner: root:root
              users:
              - name: ubuntu
                ssh_authorized_keys:
                # - ssh-rsa ## uncomment and set your ssh key here 
                sudo: ALL=(ALL) NOPASSWD:ALL
                lock_passwd: false
                plain_text_passwd: 'ubuntu'
                shell: /bin/bash
              runcmd: 
              - /root/install-nginx.sh